spring:

    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

    datasource:
        url: jdbc:mysql://104.131.116.53/sharingbox
        username: sharingboxuser
        password: sharingbox

    jpa:
      properties:
        hibernate.hbm2ddl.auto: update
        hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        hibernate:
          current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
          ddl-auto: update 
    
    
    
server:
  port: 8080
            